# Generated by Django 5.1.1 on 2024-09-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={},
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="attempt_date",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="mailingattempt",
            name="response",
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Неудачно")], max_length=10
            ),
        ),
    ]
